language: C

os:
  - linux

cache:
  - apt

env:
  global:
    - COVERAGE=1

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - lcov
      - cpanminus

install:
  - if [ "$CC" == "clang" ]; then COVERAGE=0; fi
  - sudo cpanm -v --notest Test::Nginx

script: make && make test

after_failure:
  - cat t/servroot/logs/error.log

after_success:
  - bash <(curl -s https://codecov.io/bash)